/*
 Generated by typeshare 1.0.0
*/

/** A single entry in the game log */
export type LogMessage = string;

export type DialogueMap = Record<number, DialogueContent>;

/**
 * A single unit change in relative position meant to be added to a `Position`
 * values intended to be either 1, 0 or -1 and transformed from a `Direction`
 */
export interface Delta {
	x: number;
	y: number;
}

/** Information about the size of a 2D space */
export interface Dimensions2d {
	width: number;
	height: number;
}

/** Represents the location of something on a 2D grid */
export interface Position {
	x: number;
	y: number;
}

export interface EntityIndex {
	idx: number;
}

/** Information about a sprite to render */
export interface SpriteUpdate {
	entity: EntityIndex;
	pos: Position;
	sprite: SpriteTexture;
}

/** Information about an entity to display to the user */
export interface EntityData {
	name: string;
	blocksLight: boolean;
	visibleToPlayer: boolean;
}

export interface DialogueContent {
	text: string;
	response_1_text?: string;
	response_1_id?: number;
	response_2_text?: string;
	response_2_id?: number;
}

/**
 * Yes I know this name sucks. What's better?
 * https://en.wikipedia.org/wiki/Body_relative_direction
 */
export enum BodyRelative {
	Up = "up",
	Down = "down",
	Left = "left",
	Right = "right",
}

/** A sprite to render that represents a visible entity */
export enum SpriteTexture {
	WallBrick = "wallBrick",
	ObjectRedSoda = "objectRedSoda",
	ObjectSewerGrate = "objectSewerGrate",
	ObjectWindow = "objectWindow",
	ObjectLadderUp = "objectLadderUp",
	ObjectLadderDown = "objectLadderDown",
	ObjectWater = "objectWater",
	ObjectWarpTeeveeFrames3 = "objectWarpTeeveeFrames3",
	FloorGrass = "floorGrass",
	FloorConcrete = "floorConcrete",
	FloorSlime = "floorSlime",
	NpcFatherNeilFrames6 = "npcFatherNeilFrames6",
	NpcFootballFrames4 = "npcFootballFrames4",
	NpcGoon1Frames4 = "npcGoon1Frames4",
	NpcGoon2Frames4 = "npcGoon2Frames4",
	NpcGoon3Frames4 = "npcGoon3Frames4",
	NpcGoon4Frames4 = "npcGoon4Frames4",
	NpcGraceJonesFrames6 = "npcGraceJonesFrames6",
	NpcKingRatFrames4 = "npcKingRatFrames4",
	NpcMallChick1Frames6 = "npcMallChick1Frames6",
	NpcMallChick2Frames6 = "npcMallChick2Frames6",
	NpcPersonFrames2 = "npcPersonFrames2",
	NpcRatFrames4 = "npcRatFrames4",
	NpcSewerKidFrames6 = "npcSewerKidFrames6",
	NpcSmallRatFrames6 = "npcSmallRatFrames6",
	NpcSlime = "npcSlime",
	PcAntBoi = "pcAntBoi",
	PcAntBoiFrames4 = "pcAntBoiFrames4",
	PcBoneyBoi = "pcBoneyBoi",
	PcBoneyBoiFrames4 = "pcBoneyBoiFrames4",
	PcGhostBoyFrames8 = "pcGhostBoyFrames8",
	PcKidZilla = "pcKidZilla",
	Empty = "empty",
}

/** A sprite to render that represents a temporary animation to show */
export enum AnimationTexture {
	AttackBatFrames4 = "attackBatFrames4",
}

/** Tell client to play audio */
export enum Sound {
	Punch = "punch",
}

/** An input interaction from the client */
export type ClientMessage = 
	| { type: "tileHover", content: Position }
	| { type: "tileClick", content: Position }
	| { type: "initialize", content?: undefined }
	| { type: "keypress", content: BodyRelative }
	| { type: "disconnect", content?: undefined }
	/**
	 * Clients should send every 30 seconds or so to
	 * keep from getting your socket closed when hosting on free services
	 */
	| { type: "keepAlive", content?: undefined };

/** Communicates information about the active game to one client */
export type ServerMessageSingleClient = 
	| { type: "tileHover", content?: EntityData }
	| { type: "entityPositionChange", content: SpriteUpdate }
	| { type: "centreCamera", content: Position }
	| { type: "updateFullGameMap", content: {
	camera: Position;
	entities: SpriteUpdate[];
}}
	| { type: "removeSprite", content: EntityIndex }
	| { type: "playSound", content: Sound }
	| { type: "showDialogue", content: {
	entity_name: string;
	dialogue_map: DialogueMap;
}}
	| { type: "showAnimation", content: {
	position: Position;
	animation: AnimationTexture;
}};

/** Communicates information about the active game to one client */
export type ServerMessageAllClients = 
	| { type: "tileClick", content: LogMessage }
	| { type: "moveCount", content: number };

